/**
 * Ambient type declarations for the `@pxe/runtime` authoring surface.
 *
 * The editor itself transpiles project components with Sucrase and injects the
 * runtime symbols, so it never type-checks. These declarations exist so the
 * user's own IDE / `tsc` can resolve `import ... from '@pxe/runtime'` in a
 * project that has no dependency on the (unpublished) workspace package.
 *
 * Written into the project via the "Generate Type Definitions" menu action as
 * `src/pxe-runtime.d.ts`; no `tsconfig.json` is created or modified.
 */
export function runtimeTypeDeclarations(): string {
  return `// Generated by Pixi Creator — do not edit by hand.
// Ambient module declarations so IDEs and tsc resolve \`@pxe/runtime\`
// without installing the (unpublished) workspace package.

declare module '@pxe/runtime' {
  type PropertyDefinition =
    | { type: 'number'; default?: number; min?: number; max?: number }
    | { type: 'string'; default?: string }
    | { type: 'boolean'; default?: boolean }
    | { type: 'enum'; values: string[]; default?: string }
    | { type: 'color'; default?: string }
    | { type: 'vec2'; default?: { x: number; y: number } }
    | { type: 'asset'; assetType?: string; default?: { assetId: string } | null }
    | { type: 'nodeRef'; default?: { nodeId: string } | null }
    | { type: 'componentRef'; componentType?: string; default?: { nodeId: string; componentId: string } | null };

  interface GameNode {
    x: number;
    y: number;
    name: string;
    readonly activeInHierarchy: boolean;
    readonly width: number;
    readonly height: number;
    view: unknown;
    getComponent<T extends Component>(type: new () => T): T | null;
    getComponents<T extends Component>(type: new () => T): T[];
  }

  abstract class Component {
    readonly id: string;
    node: GameNode;
    enabled: boolean;
    readonly started: boolean;
    onLoad?(): void | Promise<void>;
    start?(): void | Promise<void>;
    update?(dt: number): void;
    lateUpdate?(dt: number): void;
    onEnable?(): void;
    onDisable?(): void;
    onDestroy?(): void;
  }

  interface ComponentDefinition<T extends Component = Component> {
    type: string;
    displayName: string;
    category: string;
    ctor: new () => T;
    properties: Record<string, PropertyDefinition>;
  }

  function defineComponent<T extends Component>(definition: ComponentDefinition<T>): ComponentDefinition<T>;

  const prop: {
    number(options?: { default?: number; min?: number; max?: number }): PropertyDefinition;
    string(options?: { default?: string }): PropertyDefinition;
    boolean(options?: { default?: boolean }): PropertyDefinition;
    enum(options: { values: string[]; default?: string }): PropertyDefinition;
    color(options?: { default?: string }): PropertyDefinition;
    vec2(options?: { default?: { x: number; y: number } }): PropertyDefinition;
    asset(options?: { assetType?: string; default?: { assetId: string } | null }): PropertyDefinition;
    nodeRef(options?: { default?: { nodeId: string } | null }): PropertyDefinition;
    componentRef(options?: { componentType?: string; default?: { nodeId: string; componentId: string } | null }): PropertyDefinition;
  };

  class Button extends Component {
    interactable: boolean;
    on(event: 'click' | 'pointerDown' | 'pointerUp', listener: () => void): () => void;
    applyProperties(): void;
  }
}

declare module '@pxe/runtime/component-api' {
  export * from '@pxe/runtime';
}
`;
}

/** Project-relative path where the generated declarations live (under `src`). */
export const typeStubPath = 'src/pxe-runtime.d.ts';
